name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'
jobs:
  build_and_push_image:
  
    runs-on: ubuntu-latest
    steps:
      # 사용할 코드를 러너에게 checkout
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Docker meta
      uses: docker/metadata-action@v3
      with:
        images: dpwns523/simple_web_image
        # pr로인한 작업-> docker tag: pr-2, master push -> docker tag: master
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          
      
      # 러너에 도커가돌아갈 수 있는 환경설치
    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1
      
      # 도커허브 로그인
    - name: Login to DockerHub                      
      uses: docker/login-action@v1                   
      with:                                          
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      # 이미지 빌드 후, 허브에 push    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . # 현재 위치의 컨텍스트 사용
        file: ./dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{steps.docker_meta.outputs.tags}}
        labelss: ${{steps.docker_meta.outputs.labels}}
        
          
